version: '3'

services:
 influxdb:
  build: .
  image: influxdb
  ports:
   - "8086:8086"
  volumes:
    - python-flask\data_influxdb
 software_project:

  image: software_project
  ports: 
   - "5000:5000"
  volumes: 
   - python-flask\venv\Scripts
  depends_on:
    - influxdb